
services:
  # 1. БАЗА (Твої оригінальні дані)
  medusa_db:
    image: postgres:16
    container_name: medusa_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=medusa
      - POSTGRES_PASSWORD=medusa
      - POSTGRES_DB=medusa_db
    restart: always
    volumes:
      - ./postgres_data_medusa:/var/lib/postgresql/data

  # 2. MEDUSA (Використовує ТВИЙ Dockerfile в корені)
  medusa:
    container_name: medusa_backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - medusa_db
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=postgres://medusa:medusa@medusa_db:5432/medusa_db
      - REDIS_URL=redis://redis:6379

  # 3. STRAPI (Окремий сервіс)
  strapi:
    container_name: strapi
    build:
      context: ./strapi-cms
      dockerfile: Dockerfile
    # --- ДОДАЙ ЦЕЙ БЛОК ---
    volumes:
      - ./strapi-cms:/srv/app
      - /srv/app/node_modules
      - /srv/app/.tmp
      - /srv/app/dist
    # ----------------------
    depends_on:
      - medusa_db
    ports:
      - "1337:1337"
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=medusa_db
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi_db
      - DATABASE_USERNAME=medusa
      - DATABASE_PASSWORD=medusa
      - CLOUDINARY_NAME=dldvbmjnm
      - CLOUDINARY_KEY=427993629986674
      - CLOUDINARY_SECRET=CHVmr1ubrnYsznx6-ZQJDdT7gOY
    env_file:
      - ./strapi-cms/.env

  # 4. REDIS & SEARCH
  redis:
    image: redis:latest
    container_name: redis
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=GN645xqX-5oda_F8fc9bYPSo_k60Z8nsPzyNWneQjss